CREATE TABLE `diaria` (
   `id` BIGINT NOT NULL AUTO_INCREMENT,
   `created_at` DATETIME(6) NOT NULL,
   `updated_at` DATETIME(6) NOT NULL,
   `logradouro` VARCHAR(60) NOT NULL,
   `numero` VARCHAR(10) NOT NULL,
   `bairro` VARCHAR(30) NOT NULL,
   `complemento` VARCHAR(100) DEFAULT NULL,
   `cidade` VARCHAR(30) NOT NULL,
   `estado` VARCHAR(2) NOT NULL,
   `cep` VARCHAR(8) NOT NULL,
   `codigo_ibge` VARCHAR(255) NOT NULL,
   `observacoes` VARCHAR(255) DEFAULT NULL,
   `quantidadeQuartos` int NOT NULL,
   `quantidadeSalas` int NOT NULL,
   `quantidadeCozinhas` int NOT NULL,
   `quantidadeBanheiros` int NOT NULL,
   `quantidadeQuintais` int NOT NULL,
   `quantidadeOutros` int NOT NULL,
   `status` VARCHAR(255) NOT NULL DEFAULT 'SEM_PAGAMENTO',
   `data_atendimento` DATETIME(6) NOT NULL,
   `tempo_atendimento` int NOT NULL,
   `preco` decimal(19,2) NOT NULL,
   `valor_comissao` decimal(19,2) NOT NULL,
   `motivo_cancelamento` VARCHAR(255) DEFAULT NULL,
   `servico_id` BIGINT NOT NULL,
   `diarista_id` BIGINT DEFAULT NULL,
   `cliente_id` BIGINT NOT NULL,   
   PRIMARY KEY (`id`),
   FOREIGN KEY (`servico_id`) REFERENCES `servico` (`id`),
   FOREIGN KEY (`diarista_id`) REFERENCES `usuario` (`id`),
   FOREIGN KEY (`cliente_id`) REFERENCES `usuario` (`id`)
);